In [1]:
import numpy as np

In [2]:
a=np.arange(6)
b=np.arange(3,9)
print a
print b

[0 1 2 3 4 5]
[3 4 5 6 7 8]


In [3]:
print a+b
print a-b
print a/b.astype(float)     # so as to get the values in float
print a**b
print b**a

[ 3  5  7  9 11 13]
[-3 -3 -3 -3 -3 -3]
[ 0.          0.25        0.4         0.5         0.57142857  0.625     ]
[     0      1     32    729  16384 390625]
[    1     4    25   216  2401 32768]


In [4]:
c=np.array([[1,2],[3,4]],int)
d=np.array([[5,6],[7,8]],int)

In [5]:
print c*d                     #Element wise multiplication

[[ 5 12]
 [21 32]]


In [6]:
np.dot(c,d)                   #Matrix Multiplication

array([[19, 22],
       [43, 50]])

In [7]:
for i in c:
    print i

[1 2]
[3 4]


In [8]:
for i,x in c:
    print i,x

1 2
3 4


In [9]:
c.prod()

24

In [10]:
#find min and max
a=np.array([3,4,2,1,4,5,7])
print 'index_number:value'
print a.argmin(),':',a.min()      # argmin gives the index number of minimum, min gives the value of minimum
print a.argmax(),':',a.max()      # argmax gives the index number of maximum, max gives the value of maximum

index_number:value
3 : 1
6 : 7


In [5]:
f=np.array([[5,2],[1,-1],[3,4]],float)
print f.shape
print f            # the dot with each element below denotes that its type is float
f=f.reshape(2,3)
print f

(3L, 2L)
[[ 5.  2.]
 [ 1. -1.]
 [ 3.  4.]]
[[ 5.  2.  1.]
 [-1.  3.  4.]]


In [7]:
#sort
f.sort()
print f
print f[0]     # first row

[[ 1.  2.  5.]
 [-1.  3.  4.]]
[ 1.  2.  5.]


In [13]:
# to sort as per column
f.sort(axis=0)            # here sorting is as per column
print f

[[-1.  2.  4.]
 [ 1.  3.  5.]]


In [14]:
print f[0].min()

-1.0


In [8]:
#for both rows minimum
print 'min:,max:',f.min(axis=1),f.max(axis=1)       #will seek min and max in row 1 and row 2
print 'min:,max:',f.min(axis=0),f.max(axis=0)       #will seek min and max in column 1 and column 2

#to get the index
print 'min:index,max:index',f.argmin(axis=1),f.argmax(axis=1)     #to get the indices

min:,max: [ 1. -1.] [ 5.  4.]
min:,max: [-1.  2.  4.] [ 1.  3.  5.]
min:index,max:index [0 0] [2 2]


In [16]:
#We can also sort using sorted except we will get a list
print f,type(f)
x=f.flatten()   # sorted can only be applied on 1-D
print x.ndim    #to get the dimension
print x,type(x)
x=sorted(x)
print x

[[-1.  2.  4.]
 [ 1.  3.  5.]] <type 'numpy.ndarray'>
1
[-1.  2.  4.  1.  3.  5.] <type 'numpy.ndarray'>
[-1.0, 1.0, 2.0, 3.0, 4.0, 5.0]


In [17]:
#extracted diagonal
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print d
print d.diagonal()
np.diag(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


array([1, 5, 9])

In [18]:
# For Boolean Array, we use any and all to check whether some are true or all true
c=np.array([False,True,False])
print any(c)
print all(c)

True
False


In [19]:
#where
g=np.arange(1,10)
print g
print np.where(g>7)    #returns the index number where the value is greater than 7

[1 2 3 4 5 6 7 8 9]
(array([7, 8], dtype=int64),)


In [20]:
f=np.array([1,7,8],int)
print np.where(f>1)  # the index numbers returned

(array([1, 2], dtype=int64),)


In [21]:
#if condition is supplied by arguements, then those are returned from x else from y
f2=np.array([3,5,6,4,9],int)
print np.where(f2>4,1,0)       # this checks each element if true then 1(as passed in where) is returned else 0 returned
print f2[f2>4]

[0 1 1 0 1]
[5 6 9]


In [22]:
#array selectors for filtering and return =ing values not index
h=np.array([[6,4],[5,9]],float)
print h[h>=6]
print h

[ 6.  9.]
[[ 6.  4.]
 [ 5.  9.]]


In [23]:
#median
med=np.array([1,4,5,8,9,2,3,6,15,16],float)
print med 
med.sort()
print med
print 'median:',np.median(med)
print np.mean(med)
#here if we change the value of any by 10 or 100 times, then the median remains ame but the mean changes.
#this value is called the outlier.


[  1.   4.   5.   8.   9.   2.   3.   6.  15.  16.]
[  1.   2.   3.   4.   5.   6.   8.   9.  15.  16.]
median: 5.5
6.9


In [24]:
med1=np.array([[10,20,30],[45,50,65],[70,85,95]])
print np.median(med1)
print np.median(med1,axis=0)
print np.median(med1,axis=1)

50.0
[ 45.  50.  65.]
[ 20.  50.  85.]


In [25]:
#mean
print np.mean(med1)
print np.mean(med1,axis=0)
print np.mean(med1,axis=1)

52.2222222222
[ 41.66666667  51.66666667  63.33333333]
[ 20.          53.33333333  83.33333333]


In [27]:
#power

p1=np.array([1,2,3],int)
print np.power(p1,2)
print p1**2

[1 4 9]
[1 4 9]
