In [1]:
import numpy as np

In [3]:
#numpy.insert(arr,obj,values,axis=None)
#Insert values along the given axis before the given Indices

In [6]:
a=np.array([[1,2],[3,4]])
print a

[[1 2]
 [3 4]]


In [7]:
np.insert(a,3,6)

array([1, 2, 3, 6, 4])

In [5]:
#if axis is not mentioned ,then array is flattened first and the values are inserted at that index ,remaining are shifted

In [8]:
np.insert(a,3,[12,11])        #6,[12,11] are only temporary


array([ 1,  2,  3, 12, 11,  4])

In [9]:
np.insert(a,2,4,axis=0)   #axis=0 denotes row

array([[1, 2],
       [3, 4],
       [4, 4]])

In [10]:
np.insert(a,2,[4,5],axis=1)   #column inserted at last

array([[1, 2, 4],
       [3, 4, 5]])

In [11]:
np.insert(a,2,[4,5],axis=0)  

array([[1, 2],
       [3, 4],
       [4, 5]])

In [12]:
#numpy.append(arr,value,axis=None)
#Append values to the end of an array

In [13]:
a

array([[1, 2],
       [3, 4]])

### Note:
 - The values must be of the correct shape (the same shape as arr).If axis is not specified,values can be any shape and will be flattened before use.
 - If axis is not given,both arr and values are flattened.
    

In [14]:
np.append(a,[7,8,9])   #add at the end of the array after flattening it.


array([1, 2, 3, 4, 7, 8, 9])

In [15]:
np.append(a,[6,7],axis=0)    #the dimentions are the same as a

array([[1, 2],
       [3, 4],
       [6, 7]])

In [16]:
a    # a will be the same


array([[1, 2],
       [3, 4]])

In [19]:
b=np.append(a,[[4,4],[5,5]],axis=1)   #dimentions of the input array must be same

In [20]:
b

array([[1, 2, 4, 4],
       [3, 4, 5, 5]])

# numpy.delete(arr,obj,axis=None)

In [23]:
np.delete(a,1,axis=1)

array([[1],
       [3]])

In [24]:
a

array([[1, 2],
       [3, 4]])