In [2]:
import numpy as np

In [4]:
#Creationg array
a=np.array([1,2,3,4])   #shift+tab for more options
print a.dtype           #shows data type of elements in a
print type(a)           #shows the type of a
print a.ndim            #shows the dimentions of a
print a                 #prints a
print a.size            #for size of a

int32
<type 'numpy.ndarray'>
1
[1 2 3 4]
4


In [5]:
a=a.astype(float)       #changes the data type of values
b=a                    #an array b will be created  as a copy of a

#for these operations size of both the arrayswill be the same.
print a+b
print b-a
print b/a
print b**a
print a**b

[ 2.  4.  6.  8.]
[ 0.  0.  0.  0.]
[ 1.  1.  1.  1.]
[   1.    4.   27.  256.]
[   1.    4.   27.  256.]


In [25]:
#2D Array

b=np.array([[1,2,3],[4,5,6]])      #array of lists(list inside list)
print b
print b.ndim
print b[0][1]                    #accessing of elements
print b[1,2]

[[1 2 3]
 [4 5 6]]
2
2
6


In [26]:
print b[1,:2]
print b[:2,1:3]
print b[1,:]
print b[:2,:1]
c=b[:2,1:2]
print type(c)
print c,c.ndim
print b[-1::-1,-2::-1]    

[4 5]
[[2 3]
 [5 6]]
[4 5 6]
[[1]
 [4]]
<type 'numpy.ndarray'>
[[2]
 [5]] 2
[[5 4]
 [2 1]]


In [6]:
#d type
print b.dtype

int32


In [7]:
c=np.array(range(9),int)     #makes a one D array
print c
c=c.reshape((3,3))
print c.shape
print c.ndim
print c

[0 1 2 3 4 5 6 7 8]
(3L, 3L)
2
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#converting array to list
k=np.array([1,2,3,],float)
b=k.tolist()
print b,type(b)
print list(k)

[1.0, 2.0, 3.0] <type 'list'>
[1.0, 2.0, 3.0]


In [9]:
#transpose of an array
p=np.array(range(6),float).reshape((2,3))
print p

print p.transpose()

[[ 0.  1.  2.]
 [ 3.  4.  5.]]
[[ 0.  3.]
 [ 1.  4.]
 [ 2.  5.]]


In [10]:
#creating one dimentional array from a multi dimentional one

r=p.flatten()
print r

[ 0.  1.  2.  3.  4.  5.]


In [11]:
x=np.array([[1,2],[3,4]],float)      #generating a 2D array
y=np.array([[5,6],[7,8]],float)
print x
print y

[[ 1.  2.]
 [ 3.  4.]]
[[ 5.  6.]
 [ 7.  8.]]


In [12]:
#in concatinaction by default axis=0  row-wise
p=np.concatenate((x,y))
print p
p.shape

[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


(4L, 2L)

In [13]:
print np.concatenate((x,y),axis=1)    #columns me add hoga


[[ 1.  2.  5.  6.]
 [ 3.  4.  7.  8.]]


In [14]:
#other ways to create an array

#arange() returns an array

t=np.arange(6)
print t.reshape((2,3))
t=t.astype(float)
print t
print np.arange(1,7,2)    #stop point is included

[[0 1 2]
 [3 4 5]]
[ 0.  1.  2.  3.  4.  5.]
[1 3 5]


In [15]:
#zeroes and ones create array

print np.ones(3,dtype=int)
print np.ones((2,2))

[1 1 1]
[[ 1.  1.]
 [ 1.  1.]]


In [6]:
print np.zeros((3,3),dtype=float)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [17]:
#zeros like and one's like

In [18]:
#to create an identity matrix (2D array)
print np.identity(4,dtype=float)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [19]:
c=np.empty((2,2))
print c

[[ 1.  1.]
 [ 1.  1.]]


In [7]:
m=np.arange(0,40,10)
print m.shape,m
print m.ndim
m=m[:,np.newaxis]   #to add a new axis
print m.shape,m
print m.ndim

(4L,) [ 0 10 20 30]
1
(4L, 1L) [[ 0]
 [10]
 [20]
 [30]]
2


In [21]:

c=np.linspace(0,1,5)    #5 equally spaced points
#start,end,num-of-points
print c

[ 0.    0.25  0.5   0.75  1.  ]
