In [1]:
from sklearn.datasets import load_iris

In [2]:
iris=load_iris() #in this data set there are 3 types of flowers and according to the data we will predict the flower type


# we will get to know that KNN will be applied as classes are there and so we have to do classification hence KNN applied

In [4]:
x=iris.data
x.shape

(150L, 4L)

In [5]:
type(x)

numpy.ndarray

In [6]:
import pandas as pd
df=pd.DataFrame(x)
df.head()

0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
4  5.0  3.6  1.4  0.2

In [7]:
y=iris.target
y.shape

(150L,)

In [13]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'],
      dtype='|S10')

In [11]:
import numpy as np
np.unique(y)  #count unique values

array([0, 1, 2])

In [12]:
np.bincount(iris.target)   #counts samples of each class

array([50, 50, 50], dtype=int64)

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=0)

In [24]:
x_train.shape

(120L, 4L)

In [19]:
from sklearn.neighbors import KNeighborsClassifier

clf1=KNeighborsClassifier(n_neighbors=3)

In [20]:
clf1.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

In [22]:
clf1.score(x_test,y_test)

0.96666666666666667

In [25]:
y_pred=clf1.predict(x_test)

In [26]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 0, 0, 2, 1, 0,
       0, 2, 0, 0, 1, 1, 0])

In [27]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0,
       0, 2, 0, 0, 1, 1, 0])

In [28]:
from sklearn.metrics import confusion_matrix

In [30]:
confusion_matrix(y_test,y_pred) #here all the non diagonal values should be 0 but we have 1 at one place it means 1 sample is misclassified

array([[11,  0,  0],
       [ 0, 12,  1],
       [ 0,  0,  6]], dtype=int64)

In [31]:
np.bincount(y_test) #out of the 3 classes that we have only 1 sample of class 2 is misclassified 

array([11, 13,  6], dtype=int64)

In [45]:
c=0
for i in range(0,len(y_pred)):
    c+=1
    if(y_pred[i]!=y_test[i]):
        print c,y_pred[i],y_test[i]
        

15 2 1


In [ ]:
# Supervised
