In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('Data Preprocessing/dataset/Data.csv')

In [3]:
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
from sklearn.preprocessing import Imputer
imp=Imputer(missing_values='NaN',strategy='mean',axis=0)    #used to fill the missing values

In [5]:
X = df.iloc[:,:-1].values
y = df.iloc[:,3].values

In [6]:
X[:,1:3] = imp.fit_transform(X[:,1:3])     #for the column salary and age

In [7]:
X     #filled the missing values by mean

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [8]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'], dtype=object)

In [9]:
X1 = pd.DataFrame(X,columns=df.columns[:-1])   #excluding the last column in the data frame

In [10]:
X1

Country      Age   Salary
0   France       44    72000
1    Spain       27    48000
2  Germany       30    54000
3    Spain       38    61000
4  Germany       40  63777.8
5   France       35    58000
6    Spain  38.7778    52000
7   France       48    79000
8  Germany       50    83000
9   France       37    67000

In [11]:
#X1['Age']=X1.Age.apply(np.around,decimals=2)   #this is used to get the value upto 2 decimal places for the specified columns

In [12]:
#X1.Salary.astype(np.float64)

In [13]:
#As the scale for the values of the column are different so we get the same scale for all the values.
#this is done to reduce the varience and to plot the graph perfectly

In [14]:
X1.Country.unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [15]:
#Encoding Categorical data so that we can implement one hot encoding
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
label=LabelEncoder()
X[:,0]=label.fit_transform(X[:,0])     #here the data passed in the fit_transform has to be in array form that is y we have chosen X and not X1
X

array([[0L, 44.0, 72000.0],
       [2L, 27.0, 48000.0],
       [1L, 30.0, 54000.0],
       [2L, 38.0, 61000.0],
       [1L, 40.0, 63777.77777777778],
       [0L, 35.0, 58000.0],
       [2L, 38.77777777777778, 52000.0],
       [0L, 48.0, 79000.0],
       [1L, 50.0, 83000.0],
       [0L, 37.0, 67000.0]], dtype=object)

In [16]:
one_hot_encoder=OneHotEncoder(categorical_features=[0])

In [17]:
X=one_hot_encoder.fit_transform(X).toarray()

In [18]:
X_new=X.astype(int)
X_new

array([[    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    30, 54000],
       [    0,     0,     1,    38, 61000],
       [    0,     1,     0,    40, 63777],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [19]:
#in X the values were in float and the values were long that is y we converted it to X_new

In [20]:
label_y=LabelEncoder()
y=label.fit_transform(y)  #as target is yes and no so 1 and 0 can be put

In [21]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=0)

In [24]:
X_train.shape

(7L, 5L)

In [25]:
X_test.shape

(3L, 5L)

In [28]:
#Feature Scaling - To scale the quantities in the features to similar values between 0-1 (normalisation) or (-1) or (+1)
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
# use min-max for normalisation this is standardisation

In [29]:
X_train=sc_X.fit_transform(X_train)    
X_test=sc_X.transform(X_test)

In [30]:
X_train

array([[ 0.8660254 ,  0.        , -0.8660254 , -0.2029809 ,  0.44897083],
       [-1.15470054,  0.        ,  1.15470054, -1.82168936, -1.41706417],
       [-1.15470054,  0.        ,  1.15470054,  0.08478949, -1.0242147 ],
       [ 0.8660254 ,  0.        , -0.8660254 ,  1.5775984 ,  1.62751925],
       [-1.15470054,  0.        ,  1.15470054, -0.04111006, -0.14030338],
       [ 0.8660254 ,  0.        , -0.8660254 ,  0.93011502,  0.94003267],
       [ 0.8660254 ,  0.        , -0.8660254 , -0.52672259, -0.43494049]])

In [ ]:
# We dont scale the target only features are scaled